### ISSUE TITLE
About compiling in latest pytorch

### ISSUE THREAD

**Issue by silent567** [vene/sparseattn#3]
Hi, thank you for sharing codes firstly.
I am considering to recompile the project using latest pytorch and other related packages.

It seems that there are some pre-compiled file like _fused_jv.pyx without source files.
My questions are then: Are they important? Is it possible to re-compile by just ignoring them without influencing the modules' functions?

Thank you very much!

**Comment by vene** [comment]
Hi; those are cython source files. They are needed, and converted to C++ automatically by setup.py. 

But this has to be done anyway by all users regardless of pytorch version.

Support for newer versions of pytorch is not a matter of (re)compilation, but of changing the Pytorch wrapper classes to conform to the new API.

**Comment by vene** [comment]
In other words, those are not "precompiled" files but source files that get compiled when you build the module. Does this help?

**Comment by silent567** [comment]
Sorry for confusing the pyx file with pyc. And thanks for replying!
