### ISSUE TITLE
Got RuntimeError: expected a Variable argument, but got NoneType

### ISSUE THREAD

**Issue by Theerit** [vene/sparseattn#9]
Hi,

I was trying to use Fusedmax() with a tensor and got the following error.
*** RuntimeError: expected a Variable argument, but got NoneType

This was observed both in Pytorch 0.4.1 and Pytorch 1.1.0.

**Comment by vene** [comment]
Hi, could you please provide a minimum code sample reproducing the issue?

**Comment by Theerit** [comment]
Thank you for your quick response, below is the code that generates the RuntimeError for me. I am not sure whether I am using the function correctly though.

P.S. During my actual run, my tensor is a 3-dimension one but I was able to replicate the error with just normal tensor.

```ruby
import torch
import torchsparseattn
a = torch.tensor([1,2,2])
fusedmax = torchsparseattn.Fusedmax()
fusedmax(a)
```

**Comment by vene** [comment]
You need a "lengths" argument too; this is implemented for masking purposes (i.e. when doing batched attention with variable-length sequences.)

Here is an example

```
In [1]: import torch
In [2]: import torchsparseattn
In [3]: a = torch.tensor([1, 2, 2], dtype=torch.double)
In [4]: lengths = torch.tensor([3])
In [5]: fusedmax = torchsparseattn.Fusedmax()
In [6]: fusedmax(a, lengths)
Out[6]: tensor([0.3333, 0.3333, 0.3333], dtype=torch.float64)
```

**Comment by vene** [comment]
(I agree this is unclear, let me add an example to the readme.)
